swagger: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:8082/api
paths:
  /employees:
    get:
      tag: "employee"
      summary: Returns a list of employees.
      description: Optional extended description in CommonMark or HTML
      responses:
        '200':
          description: A JSON array of employees.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
    post:
      tag: "employee"
      summary: Creates a new employee.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error

  /employees/{id}:
    put:
      tag: "employee"
      summary: Update employee by id.
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
    delete:
      tag: "employee"
      summary: Delete employee by id.
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '201':
          description: Deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
components:
  schemas:
    Employee:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'kamron'
        surName:
          type: string
          example: 'odilov'
        department:
          type: string
          example: 'safenetpay'
        salary:
          type : number
          example: 500